consul:
  - host: consul.lab.local
    port: 8500
    token: None
    scheme: http
    consistency: default
    dc: None
    verify: True
    cert: None
    clear: True
    path: thunder
  
  ## If one consul server, two is better right
  # - host: 127.0.0.1
  #   port: 8500
  #   token: None
  #   scheme: http
  #   consistency: default
  #   dc: None
  #   verify: True
  #   cert: None
  #   clear: False
  #   path: projects